Разметил главную страницу
htmlacademy-adaptive/1036301-mishka-21 pull request #2
Opened 2020-11-16 06:00 UTC by sakralbar0192

Создал файлы для разметки внутренних страниц и перенес туда разметку шапки и подвала из главной страницы

2020-11-17 04:13 UTC, MiloTheFish8 reviewed
Перед тем, как отправлять pull-request старайся проверять сборку на ошибки линтера (команда `npm run test` локально в терминале делает примерно тоже самое, что трэвис  в репозитории). Плохой практикой считается отправлять pull request, который не прошел тесты/линтер.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +          <a href="" class="product-of-the-week__button">ЗАКАЗАТЬ</a>
Кнопки на страницах используются в разных блоках, можно сделать отдельным блоком с классом `button`, иначе придется для каждой кнопки/ссылки стили дублировать в каждом блоке.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +          <h2 class="rewiews-title">Отзывы</h2>
Если это элемент блока, именование класса неверно с точки зрения БЭМ.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +          <a href="review.html" class="reviews-button">Написать</a>
Тоже самое, что и с кнопкой выше (класс button для кнопок-ссылок), текущий класс если является элементом блока, то снова неверное именование по БЭМ.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +          <div class="reviews-controls">
Тоже самое, что и по элементам выше (если элемент блока, то надо поправить именование класса согласно БЭМ).

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +        <h2 class="visually-hidden">Как нас найти</h2>
Это лишнее. Суть контактов? По контактам можно найти организацию, человека, так что адрес, телефон, мэйл, даже карта - это все контакты.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +          <div class="how-find-us__contacts">
Блок был find-us, а здесь how-find-us, ошибка?

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +            <h3 class="contacts__title">Контакты</h3>
Элемент используется без блока.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +        <div class="find-us__map"></div>
Где изображение карты? Можно не добавлять сами картинки, но тэг и заглушку нужно добавить на данном этапе.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +        <a href="feedback.html" class="find-us__button button">Напишите нам</a>
Вот здесь класс блока button добавил, молодец.

2020-11-17 04:13 UTC, MiloTheFish8 commented on source/index.html
> +        <li class="social__item"><a href="">Instagramm</a></li>
И здесь элемент без блока используется.

2020-11-17 04:14 UTC, MiloTheFish8 requested changes
Также на других страницах проверь, чтобы аналогичные ошибки были исправлены.

2020-11-17 13:10 UTC, sakralbar0192 commented on Readme.md
> +
Это я пытался лучше понять GIT  и в консоли переключал ветки, а в редакторе что то менял. В понимании работы ГИТа это, правда, совсем не помогло

2020-11-18 03:46 UTC, sakralbar0192 commented on source/index.html
> +          <h3 class="product-of-the-week__product-name">Вязаные корзинки</h3>
Мне все таки это решение кажется верным, потому что "товар недели" - это не метка "new" в данном контексте. Мне видится, что это заголовок. описывающий контент, который находится внутри блока, озаглавленного этим заголовком) вообщем, завтра товаром недели может стать какой нибудь свитер или что то еще, а блок так и останется блоком с товаром недели, отсюда и такая структура заголовков. Может я что то не правильно понимаю - объясни, пожалуйста.

2020-11-18 03:50 UTC, sakralbar0192 commented on Readme.md
> +
Это я игрался с ГИТом. Переключался на ветку, вносил изменения, переключался на другую ветку. Мне хотелось понять как я могу увидеть более ранние версии своих проектов или версии проектов из других веток. Нужно сказать, что в итоге я так ничего и не понял. Имя ветки в редакторе кода сменялось, но в самом файле все оставалось таким же, каким я сохранял его в последний раз, даже если я делал это в другой ветке)

2020-11-19 03:56 UTC, MiloTheFish8 requested changes

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
> +    <button class="nav-toggle page-header__nav-toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
Подумай, является ли кнопка открытия меню отдельным блоком или все-таки относится к навигации?

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
> +    <nav class="additional-nav page-header__additional-nav">
Это меню надо было просто выделить из основного списка ссылок, нет необходимости оборачивать еще и в дополнительный nav, так как по сути все это меню является навигацией по сайту.

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
> +        <a href="#" class="button main-suggestion__button">ЗАКАЗАТЬ</a>
В разметке не должно быть стилизации, текст лучше всего набирать так, как он выглядит в статье, например, а заглавные буквы в стилях оформишь для кнопки.

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
>          </div>
В макете несколько отзывов, их тоже надо добавить в разметку, также имеет смысл разделить (в лекции должны были показывать, как это делается с точки зрения БЭМ) на 2 логических блока (отзывы и слайдер).

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
> +        <div class="controls reviews__controls">
Если разделить блоки по функциональности, тогда и контролы можно будет включить в блок слайдера (по сути отдельно от слайдера они и смысла-то не имеют, чтобы выделать в самодостаточный блок).

2020-11-19 03:56 UTC, MiloTheFish8 commented on source/index.html
> +      <h2 class="visually-hidden">Контакты</h2>
В макете заголовок виден.

2020-11-20 05:34 UTC, MiloTheFish8 approved these changes

2020-11-20 05:34 UTC, merged