Создал структуру препроцессорных файлов, задал тектовые параметры бло…
htmlacademy-adaptive/1036301-mishka-21 pull request #5
Opened 2020-11-21 14:09 UTC by sakralbar0192

…кам, задал цвет текста и цвет фона, задал некоторые отступы, используя фиксированную ширину отцентровал контент

2020-11-23 14:25 UTC, MiloTheFish8 requested changes

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/index.html
> +        <button class="main-nav__toggle" type="button"><span>Открыть меню</span></button>
Почему удалил класс visually-hidden? (Здесь и ниже)

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/index.html
> +        <p class="main-suggestion__text">Экологически чистая пряжа,<br/>ручная работа. Доступны в шести<br/>расцветках, и трех размерах.</p>
Есть блоки, в которых br можно использовать (задумка дизайнера), но есть блоки, в которых этого делать не нужно. Например, в данном случае текст будет меняться довольно часто, здесь явно не было задумано, чтобы переносы были именно такими (подумай о том, что браузеры по-разному обрабатывают шрифты, из-за подобной расстановки <br> в некоторых случаях может получиться перенос совсем не там, где он нужен.

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/blocks/button.less
> +  padding: 16px 0 16px 0;
Отступы лучше по бокам в том числе предусмотреть, сделать поменьше ширину. (Подумай о ситуации, когда у тебя в кнопке будет много текста).

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/blocks/button.less
> +  text-align: center;
Старайся группировать стили по стайлгайду (была ссылка в материалах еще на первом курсе на гайд академии и как правильно группировать стили).

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/blocks/button.less
> +    background: linear-gradient(0deg, #444444, #444444);
Почему просто не `background-color: #444444;`? Более того, опасно переопределять свойство `background` целиком, может получиться так, что случайно изменишь то, что не нужно было.

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/blocks/page-footer/page-footer.less
> +  &__logo {
Ниже добавила ссылку на критерий, по которому подобные селекторы не пройдут.

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/blocks/page-main/about-us.less
> +    width: 320px;
Всем блокам отдельно задаешь ширину, почему бы не создать отдельный блок-контейнер, которые будет отвечать за ширину контента и отбивать контент от краев экрана.

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/style.less
> +@import "blocks/page-footer/social.less";
Из-за того, что нет данного файла, сборка не работает, проверял?

2020-11-23 14:25 UTC, MiloTheFish8 commented on source/less/style.less
> +@import "blocks/page-header/site-list.less";
Лучше использовать плоскую структуру для файлов, также как мы делаем это в разметке, иначе пропадает смысл БЭМ (независимость блоков), что если у нас дополнительно меню из шапки перейдет в другой блок?

2020-11-25 02:05 UTC, sakralbar0192 commented on source/index.html
> +        <button class="main-nav__toggle" type="button"><span>Открыть меню</span></button>
чтобы на первом этапе стилизации было понятно, где и какой элемент. Кнопка без подписи выглядела совсем уж плохо и я убрал этот класс, по ходу дальнейшей стилизации я обязательно верну все необходимые классы на место

2020-11-25 02:08 UTC, sakralbar0192 commented on source/index.html
> +        <p class="main-suggestion__text">Экологически чистая пряжа,<br/>ручная работа. Доступны в шести<br/>расцветках, и трех размерах.</p>
Спасибо за это замечание. br поставил потому что на всех трех макетах форматирование никак не меняется и я посчитал, что имеет смысл реализовать это с помощью разметки. По поводу разной обработки шрифтов браузерами могу сказать, что представление об этом у меня весьма смутное)

2020-11-25 02:09 UTC, sakralbar0192 commented on source/less/blocks/button.less
> +    background: linear-gradient(0deg, #444444, #444444);
на самом деле, у меня тоже был такой вопрос только к макету - это свойство я скопировал оттуда. Исправил.

2020-11-25 02:16 UTC, sakralbar0192 commented on source/less/blocks/page-main/about-us.less
> +    width: 320px;
На самом деле, я так бы и сделал, впоследствии. Так я делал и в своем первом проекте, но в демке барбершопа обертку блоков задавали, как элемент этих блоков. Я думал, что дальше в демках по стилизации будет применен прием с селектором поиска в конце строки или что то вроде того. Исправил

2020-11-26 05:00 UTC, Yoona8 requested changes

2020-11-26 05:00 UTC, Yoona8 commented on source/less/blocks/about-us.less
> +  padding-bottom: 30px;
Это лучше не `padding`, а `margin` делать (верхний отступ правильно, комментарий только к нижнему относится).

2020-11-26 05:00 UTC, Yoona8 commented on source/less/blocks/about-us.less
> +  line-height: 20px;
Опасно использовать свойство `line-height` в абсолютных единицах без `font-size`, либо допиши размер шрифта явно (даже в том случае, если получится дублирование), либо добавь нужную высоту строки там, где задается шрифт.

2020-11-26 05:00 UTC, Yoona8 commented on source/less/blocks/contacts.less
> +  margin-top: 8px;
Отступы лучше всего направлять в одном направлении (одинаково во всех блоках на всем макете, то есть либо везде сверху вниз контент отбивать, либо снизу вверх, самому же удобнее работать будет, исключение составляет только отступ `header` или `footer`, так как иногда удобно отбить от основного контента их, а не сам контент). Также предпочтительное направление все-таки сверху-вниз, так как для человека это естественно (в таком ритме мы читаем).

2020-11-26 05:00 UTC, Yoona8 commented on source/less/blocks/contacts.less
> +  margin-bottom: 10px;
Не совсем поняла, для чего здесь этот нижний отступ. Отступ до подвала будет либо отступом от большого блока с основным контентом (что было бы правильно), либо отступ от самого блока контактов, но вложенной в несколько блоков кнопкой отбивать подвал - совсем не удобно, так как это тот контент, который легко может поменять свое положение, гораздо удобнее, если отступ блока все-таки будет висеть на блоке.

2020-11-26 05:00 UTC, Yoona8 commented on source/less/blocks/main-nav.less
> +    min-height: 80px;
Лучше в данном случае не высотой ограничивать, а добавить просто соответствующие отступы, минимальную высоту используют больше в тех блоках, где отступы довольно странные (например, отступы в hero блоке - гигантские и вероятно они там такие не нужны).

2020-11-26 06:05 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
> +  padding-bottom: 30px;
Исправил. Объясни, пожалуйста, почему margin лучше?

2020-11-27 07:49 UTC, Yoona8 commented on source/catalog.html
> +  <link rel="stylesheet" href="css/normalize.css">
Этот файл у тебя уже подключен в общий бандл стилей, дублировать не нужно.

2020-11-27 07:49 UTC, Yoona8 commented on source/less/blocks/about-us.less
> +  padding-bottom: 30px;
Например, верхний отступ у нас относится непосредственно к элементу, так как в нем находится иконка, а нижний в данном случае нужен только для того, чтобы создать пространство между элементами. Посмотри на макеты для разных экранов, там он легко меняется, создавая больше воздуха между элементами. Он будто бы не относится ни к тому, ни к другому элементу, такой отступ обычно делают при помощи `margin`.

2020-11-27 08:06 UTC, Yoona8 approved these changes

2020-11-27 08:06 UTC, merged