сверстал главную страницу
htmlacademy-adaptive/1036301-mishka-21 pull request #8
Opened 2020-12-02 07:57 UTC by sakralbar0192

2020-12-07 19:08 UTC, Hikikomori commented on source/less/global/variables.less
>  @white-3: #ECECEC;
Надо бы под именованием поработать. Вот этот цвет к примеру ни разу не белый. Это раз.

Во вторых, смысл цветовых переменных в том, чтобы в одном месте цвет заменить, и везде он поменялся. В связи с этим называть переменные именами цветов плохая идея, т.к в теории может возникнуть ситуация, когда захотят поменять цвета, и допустим синий цвет записанный в переменную `@red` будет выглядеть крайне странно. Лучше называть переменные по месту применения. Например `@primary-color`, `@button-color` и т.д.

Тут я тебя заставлять переделывать не буду, но на будущее советую запомнить.

2020-12-09 04:52 UTC, sakralbar0192 commented on source/less/global/variables.less
>  @white-3: #ECECEC;
Понемногу буду переделывать, к концу работы полностью изменю имена на более подходящие

2020-12-09 04:52 UTC, sakralbar0192 commented on source/less/blocks/order-form.less
> +    appearance: none;
Исправлю в ветке со стилизацией страницы формы

2020-12-09 04:52 UTC, sakralbar0192 commented on source/form.html
> +            <label class="order-form__label order-form__label--checkbox">Оранжевый<input class="order-form__input--checkbox" type="checkbox" name="color-orange"></label>
Исправлю в ветке со стилизацией страницы формы

2020-12-09 04:52 UTC, sakralbar0192 commented on source/form.html
> +          <label class="order-form__label order-form__label--radio">Аксессуар для интерьера<input class="order-form__input order-form__input--radio" type="radio" name="product-type" value="Аксессуар
Исправлю в ветке со стилизацией страницы формы

2020-12-09 04:53 UTC, sakralbar0192 commented on source/form.html
> +            <label class="order-form__label order-form__label--name">Отчество:<input class="order-form__input order-form__input--text order-form__input--name" type="text" placeholder="Отчество, если
вообще - да, пересмотрю в ближайшее время, исправлю в ветке со стилизацией страницы формы

2020-12-09 04:54 UTC, sakralbar0192 commented on source/form.html
> +          <label class="visually-hidden" for="add">Дополнительная информация</label><textarea class="order-form__textarea" name="additional-information" rows="6"  placeholder="Опишите все ваши пожела
Видимо что то экспериментировал и забыл исправить. Исправлю в ветке со стилизацией страницы формы

2020-12-09 04:54 UTC, sakralbar0192 commented on source/index.html
> +            <dd class="contacts__value contacts__value--underlined">info@mimimishkashop.ru</dd>
Уверен, что ссылка) исправил

2020-12-09 04:55 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
> +    padding-left: 175px;
все в соответствии с макетом, вроде бы

2020-12-09 05:00 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
>        background-image: url("../../img/icon-2.svg");
Я здесь рассматривал три способа реализации: с помощью флексов, тогда добиться соответствия макету мне удалось только с помощью смены ордеров пунктов списка.
С помощью гридов с  первичным заполнением столбцов, с помощью свойства grid-auto-flow: column;. 
Так же был вариант создать два разных списка и позиционировать их флексами, но этот вариант мне понравился меньше всех.
в итоге сейчас я остановился на втором варианте с гридами. Но у него есть весомый минус в виде появления горизонтальной полосы прокрутки при переполнении контентом.
Пожалуйста, подскажи, какой вариант реализации в данном случае является наиболее оптимальным и правильным

2020-12-09 05:01 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
>    }
Я здесь рассматривал три способа реализации: с помощью флексов, тогда добиться соответствия макету мне удалось только с помощью смены ордеров пунктов списка.
С помощью гридов с  первичным заполнением столбцов, с помощью свойства grid-auto-flow: column;. 
Так же был вариант создать два разных списка и позиционировать их флексами, но этот вариант мне понравился меньше всех.
в итоге сейчас я остановился на втором варианте с гридами. Но у него есть весомый минус в виде появления горизонтальной полосы прокрутки при переполнении контентом.
Пожалуйста, подскажи, какой вариант реализации в данном случае является наиболее оптимальным и правильным

2020-12-09 05:01 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
>        background-image: url("../../img/icon-2.svg");
Не совсем понял суть замечания, поясни, пожалуйста

2020-12-09 05:07 UTC, sakralbar0192 commented on source/less/blocks/order-form.less
> +    &::before {
А как тогда реализовывать дизайнерское отображения чекбоксов и радиокнопок, где их вид зависит от состояния самого чекбокса (checked/ или нет).
И в данном случае псевдоэлемент вполне рабочий и можно потыкать и посмотреть результат. Насколько я знаю псевдоэлементы не работают только у инпутов с текстовым типом содержания. Поясни, пожалуйста, как быть.

2020-12-09 05:11 UTC, sakralbar0192 commented on source/less/blocks/site-list.less
> +    max-width: 42%;
В зависимости от ситуации я прописываю ограничение по ширине с тем, чтобы блок при расширении оставался приемлемым на вид и не залезал на/под другие блоки. В хедере десктопной версии это сделано, чтобы при переполнении контентом пункты не залезли под логотип. В hero-блоке максимальная ширина задана ввиду ограниченной ширины волнистой декоративной линии. В правках постарался отказаться от % и не ограничивать ширины блоков без необходимости

2020-12-09 15:51 UTC, Hikikomori commented on source/less/blocks/about-us.less
>        background-image: url("../../img/icon-2.svg");
Обычно струкутура файлов в сборке какая-то такая 

```
build
  ./css
    style.css 
  ./img
    image.jpeg
  index.html
```
И чтобы из css файла попасть в папку с картинками, нужно подняться только на один уровень вверх.


А у тебя получается что-то такое

```
build
  ./css
    ./???
      style.css 
  ./img
    image.jpeg
  index.html
```

2020-12-09 15:54 UTC, Hikikomori commented on source/less/blocks/about-us.less
>    }
А что тебе не нравится в предложенном мной способе ?
Да, два списка, и что ?

2020-12-10 01:16 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
>        background-image: url("../../img/icon-2.svg");
Проверил. Результирующая структура файлов такая, какой и должна быть. Двойной выход на уровень выше был потому что код я пишу в less файле, а он находится в папке blocks, отсюда и двойной выход.
Странно то, что картинка отображается если указать двойной выход на уровень выше так же как и если указать только один выход. Исправлю в ближайшее время

2020-12-10 02:26 UTC, sakralbar0192 commented on source/less/blocks/about-us.less
>    }
Наверное дело в том, что я плохо представляю как происходит наполнение сайта контентом, но мне кажется, что два списка - там, где, по-логике, должен быть один - плохая идея. Как человек, наполняющий сайт поймет в какой список нужно добавить элемент? А если элемента будет 3? Так же такой подход, на мой взгляд, повлечет за собой несколько дополнительных свойств для списков, как например align-items: top в случае построения сетки списков на флексах, чтобы элементы одного списка не растягивались из-за того, что в другом списке будет больше элементов. 
Вообще, я считаю - проблема в макете: если дизайнер расположил преимущества в соответствии с логикой их важности, то впоследствии он эту логику сам и нарушил, потому что европейский человек читает справа-налево и сверху-вниз. Будь это реальный проект - я бы попросил его исправить это, чтобы не создавать лишних стилей и тегов в коде. Ну а в данном случае - использование ордеров, на мой взгляд, опять же, самый оптимальный вариант. Объясни, пожалуйста, почему он не подходит

2020-12-10 06:10 UTC, sakralbar0192 commented on source/form.html
> +          <label class="order-form__label order-form__label--radio">Аксессуар для интерьера<input class="order-form__input order-form__input--radio" type="radio" name="product-type" value="Аксессуар
или нет. Мне тяжело ориентироваться в коде, когда слишком увлекаюсь вложенностью, поэтому инпуты вынес в отдельный модификатор

2020-12-23 13:32 UTC, urazaev requested changes
Неплохая, почти готовая работа, но давай пойдем по порядку. Я проверяю сейчас сеточные свойства и будем смотреть по ним.
1. Тут не совсем про сетки, но в файле `fonts.less` нужно поправить пути, например ` url("/fonts/opensans.woff2")` на относительный ` url("../fonts/opensans.woff2")` по скольку у тебя не всегда сайт может быть размещен в корневой директории и твой вариант пути работать не будет, вот кстати в интерфейсе академии наживаешь когда собрать проект сайт публикуется и не в корневой директории https://htmlacademy-adaptive.github.io/1036301-mishka-21/8/ обрати внимание что тут уже не работают твои пути до шрифтов.
2. Контентная область на ширине больше desktop должна центрироваться и ограничиваться https://yadi.sk/d/x6gCO-ROuuUxsA как в макете https://yadi.sk/d/PshlK2yN3flaTA а у тебя же тянется..
3. По ТЗ https://up.htmlacademy.ru/adaptive/21/project/mishka#mishka-3-2 фоны которые упираются в край макета, нужно тянуть на всю ширину вьюпорта , у тебя же так не происходит из-за ограниченного `max-width` https://yadi.sk/d/NQr-9yxWBwVqhg

2020-12-23 13:32 UTC, urazaev commented on source/less/blocks/main-suggestion.less
> +    position: absolute;
Тут так же желательно сеточный текстовый блок без абсоюта повесить, далее прочекай такие места в проекте, есть еще кейсы. Нужно поработать над этим.

2020-12-24 08:06 UTC, merged